# Generated by Django 4.2.4 on 2023-11-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_level_letter_alter_word_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(default='noun', max_length=50),
        ),
    ]
