# Generated by Django 4.2.4 on 2023-11-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20231119_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('ps', 'Practice Session'), ('normal', 'Normal')], default='normal', max_length=6),
        ),
        migrations.AddField(
            model_name='message',
            name='practice_session_word',
            field=models.ManyToManyField(related_name='practice_session_word_messages', to='chatbot.word'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lesson_progress',
            field=models.CharField(choices=[('ps0', 'Practice Session 0'), ('ps1', 'Practice Session 1'), ('ps2', 'Practice Session 2'), ('ps3', 'Practice Session 3'), ('ps4', 'Practice Session 4'), ('ps5', 'Practice Session 5'), ('st0', 'Sentence Test 0'), ('st1', 'Sentence Test 1'), ('st2', 'Sentence Test 2'), ('st3', 'Sentence Test 3'), ('st4', 'Sentence Test 4'), ('st5', 'Sentence Test 5'), ('vt', 'Verse Test'), ('t', 'Tafseer')], default='ps0', max_length=3),
        ),
    ]
